---
- name: Jenkins Playbook
  hosts: webservers
  user: ansible
  become: true
  connection: ssh

  tasks:
    - name: install java on hosts
      yum:
        name: java
        state: installed

    - name: download jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: donload jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install jenkins
      yum:
        name: jenkins
        state: installed

    - name: start jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes










